spring:
  config:
    import:
      - optional:file:ET-user/.env[.properties]
      - "classpath:jwtTokenSetting.properties"
  application:
    name: ET-user
  datasource:
    url: jdbc:mysql://${USER_DB_HOST}:${USER_DB_PORT}/${USER_DB}
    username: ${USER_DB_USER}
    password: ${USER_DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:8761/eureka
