spring:
  config:
    import: optional:file:ET-core/.env[.properties]
  application:
    name: ET-core
  datasource:
    url: jdbc:mysql://${CORE_DB_HOST}:${CORE_DB_PORT}/${CORE_DB}
    username: ${CORE_DB_USER}
    password: ${CORE_DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 30000      # 유휴 커넥션 제거 시간 증가 (30초 → 60초)
      max-lifetime: 1800000    # 커넥션 최대 수명 증가 (30분 → 1시간)
      connection-timeout: 30000 # 커넥션 획득 대기 시간 유지 (30초)
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true

server:
  tomcat:
    threads:
      max: 400
    connection-timeout: 20000
    keep-alive-timeout: 10000
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: ${HOST_NAME}

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE