name: Deploy Core Module
on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'ET-core/**'

jobs:
  deploy-core-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # 도커 로그인

      - name: Build and Push Core Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./ET-core/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/et-core:latest


      - name: Create .env and Deploy Core
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.BASTION_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            ssh -tt core-mod "cd /home/ubuntu && \
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/et-core:latest && \
            docker rm -f ET-core || true && \
            docker run -d --name ET-core --env-file .env -p 8082:8082 ${{ secrets.DOCKERHUB_USERNAME }}/et-core:latest"
