name: Deploy Eureka Trigger

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'ET-eureka/**'

jobs:
  deploy-eureka:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        # Github 소스 가져오기

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # 도커 로그인

      - name: Build and Push Eureka Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./ET-eureka/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/et-eureka:latest

      - name: Create .env and Deploy Eureka
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EUREKA_HOST }}      # Eureka가 배포될 Public 서버 주소
          username: ${{ secrets.EC2_USERNAME }}    # 해당 서버의 SSH 사용자명
          key: ${{ secrets.AWS_SSH_KEY }}      # SSH 접속용 비밀키
          script: |
            cd /home/ubuntu
            
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/et-eureka:latest
            docker rm -f ET-eureka || true
            docker run -d --name ET-eureka -p 8761:8761 ${{ secrets.DOCKERHUB_USERNAME }}/et-eureka:latest


