name: Deploy Pipeline Module
on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'ET-pipeline/**'

jobs:
  deploy-pipeline-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # 도커 로그인


      - name: Build and Push Pipeline Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./ET-pipeline/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/et-pipeline:latest



      - name: Deploy Pipeline
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.BASTION_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            ssh -tt pipe-mod "cd /home/ubuntu && \
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/et-pipeline:latest && \
            docker rm -f ET-pipeline || true && \
            docker run -d --name ET-pipeline --env-file .env -p 8084:8084 ${{ secrets.DOCKERHUB_USERNAME }}/et-pipeline:latest"
